import { EMAIL_OSAMA, MAIN_BRANCH_EMAIL } from './constants'
import type { BranchRecord } from './types'

const DEFAULT_HOURS = 'السبت - الخميس: 8 ص - 12 م | الجمعة: 4 م - 12 م'
const now = new Date().toISOString()

export const DEMO_BRANCHES: BranchRecord[] = [
  {
    id: 'branch-1',
    name: 'الفرع الرئيسي',
    address: 'طريق المطار',
    city: 'المدينة المنورة',
    phone: '050 459 0002',
    email: MAIN_BRANCH_EMAIL,
    hours: DEFAULT_HOURS,
    map_url: 'https://maps.app.goo.gl/JJNXk515GhDxqu889?g_st=iw',
    image_url: null,
    is_main: true,
    is_active: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'branch-2',
    name: 'فرع طريق المطار 2',
    address: 'طريق المطار',
    city: 'المدينة المنورة',
    phone: '055 588 7324',
    email: EMAIL_OSAMA,
    hours: DEFAULT_HOURS,
    map_url: 'https://maps.google.com/?q=24.482824,39.630497',
    image_url: null,
    is_main: false,
    is_active: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'branch-3',
    name: 'فرع طريق سلطانه',
    address: 'طريق سلطانه',
    city: 'المدينة المنورة',
    phone: '053 118 8874',
    email: EMAIL_OSAMA,
    hours: DEFAULT_HOURS,
    map_url: 'https://maps.app.goo.gl/GXRSGgLgdAj6gvJi6?g_st=iw',
    image_url: null,
    is_main: false,
    is_active: true,
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'branch-4',
    name: 'فرع العالية',
    address: 'العالية',
    city: 'المدينة المنورة',
    phone: '055 666 3589',
    email: null,
    hours: DEFAULT_HOURS,
    map_url: 'https://maps.google.com/?q=24.419773,39.620392',
    image_url: null,
    is_main: false,
    is_active: true,
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'branch-5',
    name: 'فرع العزيزية',
    address: 'العزيزية',
    city: 'المدينة المنورة',
    phone: null,
    email: null,
    hours: DEFAULT_HOURS,
    map_url: 'https://maps.app.goo.gl/agZ4fhN7CEykbHva8?g_st=iw',
    image_url: null,
    is_main: false,
    is_active: true,
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'branch-6',
    name: 'فرع ينبع',
    address: 'ينبع',
    city: 'ينبع',
    phone: '055 335 7178',
    email: null,
    hours: DEFAULT_HOURS,
    map_url: 'https://maps.google.com/?q=24.086933,38.064159',
    image_url: null,
    is_main: false,
    is_active: true,
    sort_order: 6,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'branch-7',
    name: 'فرع ضباء',
    address: 'ضباء',
    city: 'ضباء',
    phone: '055 588 6210',
    email: null,
    hours: DEFAULT_HOURS,
    map_url: 'https://maps.app.goo.gl/VAahiHjbq2Hr49ch7?g_st=iw',
    image_url: null,
    is_main: false,
    is_active: true,
    sort_order: 7,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'branch-8',
    name: 'فرع تبوك',
    address: 'تبوك',
    city: 'تبوك',
    phone: '055 588 6412',
    email: null,
    hours: DEFAULT_HOURS,
    map_url: 'https://maps.google.com/?q=28.399940,36.530735',
    image_url: null,
    is_main: false,
    is_active: true,
    sort_order: 8,
    created_at: now,
    updated_at: now,
  },
]