/** نصوص الموقع — فصحى سعودية بسيطة + كلمات إنجليزية */
export const copy = {
  shared: {
    pricesIncludeVat: 'جميع الأسعار شاملة ضريبة القيمة المضافة (15%)',
  },
  site: {
    tagline: 'ايجار سيارات يومي وشهري في السعودية',
    heroTitle: 'وجهتك الأولى لتأجير السيارات',
    heroSubtitle:
      'تأجير سيارات يومي وشهري في أنحاء المملكة - أسعار مناسبة وأسطول حديث',
    heroCta: 'احجز سيارتك الآن',
    browseCars: 'تصفح السيارات',
    whatsapp: 'تواصل واتساب',
  },
  nav: {
    home: 'الرئيسية',
    cars: 'السيارات',
    about: 'من نحن',
    branches: 'فروعنا',
    bookNow: 'احجز سيارتك الآن',
    admin: 'لوحة الإدارة',
  },
  home: {
    whyUs: 'ليش تختار الخضر؟',
    whyUsSub: 'تجربة Car Rental سهلة ومريحة',
    featured: 'أسطول السيارات',
    featuredSub: 'كل سياراتنا المتاحة — إيجار يومي أو شهري',
    viewAll: 'عرض الكل',
    promos: 'عروضنا الحالية',
    promosSub: 'عروض الصيف والتوفير — لفترة محدودة',
    visitBranch: 'زورنا في فرعنا الرئيسي',
    openMap: 'افتح الخريطة',
    allBranches: 'جميع الفروع',
    quickSearch: 'احجز الآن',
    quickSearchSub: 'حدد التواريخ وشوف السيارات المتاحة',
    fromDate: 'من تاريخ',
    toDate: 'إلى تاريخ',
    searchCars: 'ابحث عن سيارة',
    newTigo7Pro: 'جديدنا — تيجو 7 برو',
    newTigo7ProSub: 'SUV عائلي — راحة وأداء على الطريق',
    brandVideoTitle: 'الخضر للسيارات',
    reviewsTitle: 'آراء عملائنا',
    reviewsSub: 'تقييمات 5 نجوم من عملائنا على Google — تجارب حقيقية في تأجير السيارات',
    reviewsCta: 'شاهد على Google',
  },
  features: [
    { title: 'أسطول متنوع', desc: 'سيارات اقتصادية وفاخرة وعائلية — على كيفك' },
    { title: 'تأمين شامل', desc: 'كل سياراتنا مؤمنة — وانت مرتاح' },
    { title: 'خدمة 24/7', desc: 'فريقنا جاهز لك أي وقت' },
    { title: 'أسعار واضحة', desc: 'بدون رسوم مخفية — السعر اللي تشوفه هو اللي تدفعه' },
  ],
  cars: {
    title: 'أسطول السيارات',
    subtitle: 'ايجار سيارة يومي أو شهري — اختر السيارة المناسبة',
    noResults: 'ما لقينا سيارات تطابق بحثك',
    perDay: '/ يوم',
    perMonth: '/ شهر',
    rentalType: 'نوع الإيجار',
    rentalDaily: 'إيجار يومي',
    rentalMonthly: 'إيجار شهري',
    dailyFleetTitle: 'إيجار يومي',
    dailyFleetSub: 'أسعار يومية مرنة — مثالية للرحلات والاستخدام القصير',
    monthlyFleetTitle: 'إيجار شهري',
    monthlyFleetSub: 'باقات شهرية بأسعار أوفر — للإقامة الطويلة والعقود الشهرية',
    bookNow: 'احجز سيارتك الآن',
    unavailable: 'غير متاحة',
    sortPrice: 'ترتيب السعر',
    sortLow: 'الأقل سعراً',
    sortHigh: 'الأعلى سعراً',
    datesSelected: 'التواريخ المحددة',
    booked: 'محجوزة',
    bookedForDates: 'محجوزة في التواريخ المحددة',
    availableForDates: 'متاحة في التواريخ المحددة',
    adminDisabled: 'موقوفة من الإدارة',
    checkDates: 'حدد التواريخ للتحقق من التوفر',
    availableOnly: 'المتاحة فقط',
    showingAvailable: 'عرض السيارات المتاحة فقط',
    pendingHold: 'طلب حجز قيد المراجعة',
    chooseBranch: 'اختر الفرع',
    selectBranchPlaceholder: '— اختر فرعك —',
    allBranches: 'كل الفروع — كل السيارات',
    browsingBranch: 'أنت تتصفح',
    clearBranch: 'عرض كل الفروع',
    noCarsInBranch: 'لا توجد سيارات في هذا الفرع حالياً',
    branchRequired: 'اختر الفرع أولاً',
    branchRequiredHint: 'حدد الفرع اللي بتستلم منه السيارة — التوفر والأسعار حسب الفرع',
    branchRequiredSearch: 'اختر الفرع عشان نعرض لك السيارات المتاحة',
    availabilityPerBranch: 'التوفر محسوب حسب الفرع المختار',
    pickBranchTitle: 'اختر فرعك أولاً',
    pickBranchSub: 'السيارات والتوفر والحجز — كلها حسب الفرع اللي تختاره',
    yourBranch: 'فرعك',
    changeBranch: 'تغيير الفرع',
    allBranchesLink: 'عرض كل الفروع على الخريطة',
    noBranchesAvailable: 'جاري تحميل الفروع — إذا ما ظهرت تواصل معنا',
    filterCategory: 'التصنيف',
    filterClass: 'الفئة',
  },
  detail: {
    back: 'العودة للسيارات',
    notFound: 'السيارة مو موجودة',
    specs: 'المواصفات',
    transmission: 'ناقل الحركة',
    fuel: 'الوقود',
    seats: 'المقاعد',
    ac: 'تكييف',
    acYes: 'متوفر',
    acNo: 'غير متوفر',
    bookThis: 'احجز سيارتك الآن',
    unavailable: 'هالسيارة مو متاحة حالياً للحجز',
    booked: 'محجوزة في الفترة المحددة',
    bookedConfirmed: 'محجوزة ومؤكدة — اختر تواريخ أخرى',
    adminDisabled: 'موقوفة مؤقتاً من الإدارة',
    featured: 'مميزة',
    availability: 'حالة التوفر',
  },
  booking: {
    title: 'حجز السيارة',
    subtitle: 'Car Rental Booking',
    step1: 'التواريخ والاستلام',
    step2: 'بياناتك',
    step3: 'تأكيد',
    selectDates: 'حدد فترة الإيجار',
    from: 'من تاريخ',
    to: 'إلى تاريخ',
    pickupTime: 'موعد الاستلام',
    pickupTimeHint: 'حدد اليوم والساعة المناسبة لاستلام السيارة',
    pickupDetails: 'تفاصيل الاستلام',
    pickupDetailsSub: 'متى ومن أي فرع تبي تستلم السيارة؟',
    pickupDay: 'يوم الاستلام',
    pickupHour: 'الساعة',
    pickupPeriod: 'الفترة',
    pickupMorning: 'صباحاً',
    pickupEvening: 'مساءً',
    choosePickupBranch: 'فرع الاستلام *',
    choosePickupBranchHint: 'اختر الفرع اللي بتستلم منه السيارة',
    promoBooking: 'حجز العرض المميز',
    promoBookingSub: 'اختر التواريخ وموعد الاستلام وأدخل بياناتك — الطلب يصل للإدارة للتأكيد',
    customerInfo: 'بيانات العميل',
    fullName: 'الاسم الكامل',
    phone: 'رقم الجوال',
    phoneCountry: 'كود الدولة',
    phoneFormatted: 'الرقم الكامل',
    email: 'البريد الإلكتروني (اختياري)',
    idNumber: 'رقم الهوية (اختياري)',
    notes: 'ملاحظات إضافية',
    notesPlaceholder: 'أي طلب خاص... مثلاً: استلام من المطار',
    priceSummary: 'ملخص السعر',
    totalDays: 'عدد الأيام',
    pricePerDay: 'السعر / يوم',
    pricePerMonth: 'السعر / شهر',
    totalMonths: 'عدد الأشهر',
    monthUnit: 'شهر',
    monthsUnit: 'أشهر',
    total: 'الإجمالي',
    submit: 'إرسال طلب الحجز',
    successTitle: 'تم إرسال طلبك!',
    successReview: 'طلبك قيد المراجعة — ستصلك رسالة واتساب عند التأكيد',
    successContactBranch: 'لتسريع تأكيد الحجز، تواصل مع فرع الاستلام:',
    successBranchPhone: 'رقم الفرع',
    successMsg: 'راح نتواصل معك قريب عشان نأكد الحجز. تقدر تتواصل معنا على الواتساب بعد.',
    successWhatsAppSent: 'أرسلنا لك رسالة على واتساب — حجزك قيد الانتظار وسنأكد لك قريباً',
    successWhatsAppPending: 'طلبك قيد المراجعة — ستصلك رسالة واتساب عند التأكيد',
    newBooking: 'حجز جديد',
    backToCar: 'العودة لتفاصيل السيارة',
    pickupBranch: 'فرع الاستلام',
    autoCalc: 'السعر يتحسب تلقائياً حسب عدد الأيام',
    next: 'التالي',
    prev: 'السابق',
    confirm: 'تأكيد وإرسال',
    errors: {
      namePhone: 'الاسم ورقم الجوال مطلوبين',
      phoneInvalid: 'رقم الجوال غير صحيح — تأكد من الكود والرقم',
      dates: 'حدد تاريخ البداية والنهاية',
      dateOrder: 'تاريخ النهاية لازم يكون بعد تاريخ البداية',
      pickupTime: 'حدد يوم ووقت الاستلام',
      pickupBranch: 'اختر فرع الاستلام',
      submit: 'ما قدرنا نرسل الطلب — حاول مرة ثانية',
      unavailable: 'السيارة غير متاحة في التواريخ المحددة — غيّر التواريخ',
    },
  },
  about: {
    title: 'من نحن',
    intro:
      'انطلقت شركة عبدالمجيد الخضر لتأجير السيارات برؤية طموحة لتكون الخيار الرائد والموثوق في قطاع التنقل بالمملكة العربية السعودية.',
    extended:
      'نحن لا نقدم مجرد سيارات للإيجار، بل نبتكر حلول تنقل متكاملة ومرنة تلبي تطلعات الأفراد وقطاع الأعمال، معتمدين على أسطول حديث ومتنوع يتجاوز 35 فرعاً استراتيجياً.',
    visionTitle: 'رؤيتنا',
    vision:
      'أن نكون الخيار المثالي والوجهة الموثوقة لحلول التنقل في المملكة، من خلال تقديم خدمات ترتقي لتطلعات عملائنا.',
    goalsTitle: 'آفاقنا الاستراتيجية',
    whyTitle: 'ليش نتميز؟',
    perks: [
      'أكثر من 35 فرعاً في أنحاء المملكة',
      'أسطول سيارات حديث ومتنوع',
      'تأجير يومي وشهري مرن',
      'حلول تأجير طويلة الأجل للشركات',
      'صيانة دورية مجانية',
      'دعم فني على مدار الساعة',
      'حجز رقمي سريع وسهل',
      'خبرة بخدمة زوار المدينة المنورة والمناطق',
    ],
  },
  profile: {
    servicesTitle: 'خدماتنا',
    servicesSub: 'حلول تأجير متكاملة للأفراد والشركات',
    fleetTitle: 'أسطولنا',
    fleetSub: 'سيارات حديثة تناسب كل الاحتياجات — Sedan، SUV، فاخرة، وتجارية',
    partnersTitle: 'أبرز شركاء النجاح',
    partnersSub: 'نفخر بشراكتنا مع كبرى المؤسسات والشركات',
    partnersCta: 'كن شريك نجاحنا القادم',
    branchesNetwork: 'شبكة فروعنا',
    branchesNetworkSub: 'نخدمكم في جميع مناطق المملكة',
  },
  branches: {
    title: 'فروعنا',
    subtitle: 'أكثر من 35 فرعاً في أنحاء المملكة — خدمة ايجار السيارات أينما كنت',
    openMap: 'افتح في خرائط جوجل',
    bookFromBranch: 'احجز من هذا الفرع',
  },
  offers: {
    title: 'العروض المميزة',
    subtitle: 'باقات الإيجار اليومي والشهري — عروض حصرية',
    pageTitle: 'عروض الإيجار المميزة',
    pageSubtitle: 'وفّر أكثر مع باقاتنا اليومية والشهرية — أسعار واضحة بدون مفاجآت',
    badge: 'عروض حصرية',
    filterAll: 'الكل',
    filterDaily: 'إيجار يومي',
    filterMonthly: 'إيجار شهري',
    viewAll: 'كل العروض',
    noOffers: 'لا توجد عروض متاحة حالياً',
    offerPrice: 'سعر العرض',
    save: 'وفّر',
    bookOffer: 'احجز العرض',
    expired: 'منتهي',
    specialDeal: 'عرض خاص',
    activePromo: 'عرض مميز مفعّل',
    monthlyHint: 'باقة شهرية — يُفضّل حجز 30 يوم',
  },
  admin: {
    login: 'تسجيل دخول الإدارة',
    demoHint: 'الوضع التجريبي: كلمة المرور admin123',
    dashboard: 'لوحة التحكم',
    cars: 'السيارات',
    offers: 'العروض المميزة',
    bookings: 'الحجوزات',
    logout: 'تسجيل الخروج',
    viewSite: 'عرض الموقع',
    toggleAvailable: 'تبديل التوفر',
    activeBookings: 'حجوزات نشطة',
    noActiveBookings: 'لا توجد حجوزات نشطة',
    availabilityControl: 'التحكم بالتوفر',
    manualOff: 'موقوفة يدوياً',
    bookedNow: 'محجوزة حالياً',
    bookingBranch: 'فرع الحجز',
    filterByBranch: 'فلترة حسب الفرع',
    allBranchesFilter: 'كل الفروع',
    carBranches: 'الفروع المتاحة',
    carBranchesHint: 'اتركه فارغاً = السيارة تظهر في كل الفروع',
    carBranchesRequired: 'حدد فرعاً واحداً على الأقل، أو اترك الكل لعرضها في كل الفروع',
    myBranchButton: 'فرعي',
    pickYourBranch: 'اختر فرعك',
    enterBranchMode: 'دخول وضع فرعي',
    exitBranchMode: 'عرض الكل',
    branchModeActive: 'وضع فرعي —',
    switchBranch: 'تبديل الفرع',
    branchModeHint: 'كل البيانات المعروضة خاصة بفرعك فقط',
  },
  footer: {
    brandAlt: 'الخضر لتأجير السيارات — عبدالمجيد الخضر لتأجير السيارات',
    desc: 'الخضر لتأجير السيارات — شركة عبدالمجيد الخضر لتأجير السيارات. ايجار وتأجير سيارات يومي وشهري بأسعار واضحة وأسطول حديث في السعودية.',
    quickLinks: 'روابط سريعة',
    contact: 'تواصل معنا',
    hours: 'ساعات العمل',
    social: 'تابعنا',
    rights: 'جميع الحقوق محفوظة',
    tagline: 'الافضل في مجال تأجير السيارات',
  },
} as const