import { asset } from './assets'
import type { FeaturedOffer } from './types'

const now = new Date().toISOString()

export const DEMO_FEATURED_OFFERS: FeaturedOffer[] = [
  {
    id: 'offer-1',
    title: 'عرض كابتيفا اليومي',
    description: 'خصم 15% على الإيجار اليومي لشيفرولية كابتيفا 2026 — عرض إجازة الصيف',
    rental_type: 'daily',
    image_url: asset('شيفرولية-كابتيفا-عروض-الصيف.jpg.jpeg'),
    badge_text: 'خصم 15%',
    price: 153,
    original_price: 180,
    car_id: '5',
    link_url: null,
    is_active: true,
    is_featured: true,
    valid_until: '2026-09-30',
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'offer-2',
    title: 'ازكارا — دبل العرض',
    description: 'عرض مميز على جيلي ازكارا 2023 للإيجار اليومي والأسبوعي',
    rental_type: 'daily',
    image_url: asset('جيلي-ازكارا-دبل-عروض-الصيف.jpg.jpeg'),
    badge_text: 'دبل العرض',
    price: 178,
    original_price: 210,
    car_id: '9',
    link_url: null,
    is_active: true,
    is_featured: true,
    valid_until: '2026-09-30',
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'offer-3',
    title: 'باقة التوفير الشهرية',
    description: 'إيجار شهري بأسعار مخفّضة — وفر أكثر مع الالتزام الشهري',
    rental_type: 'monthly',
    image_url: asset('عروض-التوفير.jpg.jpeg'),
    badge_text: 'وفر 20%',
    price: 2800,
    original_price: 3500,
    car_id: '2',
    link_url: null,
    is_active: true,
    is_featured: true,
    valid_until: '2026-12-31',
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'offer-4',
    title: 'لينك آند كو 03 — شهري',
    description: 'باقة إيجار شهرية لسيارة لينك آند كو 03 2024 بسعر مميز',
    rental_type: 'monthly',
    image_url: asset('بوست-لينك-اند-كو-٠٣.jpg.jpeg'),
    badge_text: 'باقة شهرية',
    price: 4500,
    original_price: 5200,
    car_id: '7',
    link_url: null,
    is_active: true,
    is_featured: true,
    valid_until: '2026-12-31',
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'offer-5',
    title: 'تويوتا يارس — عروض الصيف',
    description: 'إيجار يومي اقتصادي — تويوتا يارس 2024 بسعر مميز للتنقل اليومي',
    rental_type: 'daily',
    image_url: asset('تويوتا-يارس-عروض-الصيف.jpg.jpeg'),
    badge_text: '85 ر.س/يوم',
    price: 85,
    original_price: 100,
    car_id: '12',
    link_url: null,
    is_active: true,
    is_featured: true,
    valid_until: '2026-09-30',
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'offer-6',
    title: 'قسّط مع تمارا',
    description: 'قسّم إيجارك على دفعات مريحة — متاح على باقات الإيجار الشهري',
    rental_type: 'monthly',
    image_url: asset('تمارا١.jpg.jpeg'),
    badge_text: 'تمارا',
    price: 0,
    original_price: null,
    car_id: null,
    link_url: '/cars',
    is_active: true,
    is_featured: false,
    valid_until: null,
    sort_order: 6,
    created_at: now,
    updated_at: now,
  },
]